{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2eaaae3c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "     Unnamed: 0  Subject  Vision Surface         X         Y\n",
      "0             0        1    Open    Firm -0.922794  0.702471\n",
      "1             1        1  Closed    Firm -0.929073  0.702471\n",
      "2             2        1    Open    Foam -0.673078  0.702471\n",
      "3             3        1  Closed    Foam -0.453918  0.702471\n",
      "4             4        2    Open    Firm -0.941319 -0.368982\n",
      "..          ...      ...     ...     ...       ...       ...\n",
      "639         639      162    Open    Foam  0.332269 -0.287135\n",
      "640         640      163  Closed    Firm -0.806407 -0.517795\n",
      "641         641      163    Open    Foam -0.112514 -0.517795\n",
      "642         642      163    Open    Firm -0.797555 -0.517795\n",
      "643         643      163  Closed    Foam -0.049677 -0.517795\n",
      "\n",
      "[644 rows x 6 columns]\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "# learning\n",
    "# author: Cheng Zheng\n",
    "\n",
    "import os\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Machine learning algorithms\n",
    "from sklearn.kernel_ridge import KernelRidge #Kernel ridge regression\n",
    "\n",
    "# Cross-validation\n",
    "'''\n",
    "GridSearchCV = Perform an optimization of the parameters. 可以保证在指定的参数范围内找到精度最高的参数\n",
    "                1. search for the best parameters for model; \n",
    "                2. automatically fit a new model on the training dataset w/ the parameters that \n",
    "                    can yield the best cross-validation performance.\n",
    "cross_val_score = to implement cross-validation in scikit-learn.\n",
    "KFold: just to divide the dataset.\n",
    "    - When an integer is passed to the cv parameter of cross_val_score():\n",
    "        cv=int (same as cv=StratifiedKFold(n_splits=int)) is used if the estimator is a classifier \n",
    "        and y is either binary or multiclass; In all other cases, KFold is used.\n",
    "'''\n",
    "from sklearn.model_selection import GridSearchCV, cross_val_score, KFold\n",
    "\n",
    "path = os.getcwd()#get current path\n",
    "path_up1Dir = os.path.dirname(path)#go up one directory\n",
    "dataset = pd.read_excel(path_up1Dir +'/x_TotalArea_y_MVPA/x_TotalArea_y_MVPA.xlsx')#to import the preprocessed dataset into a variable\n",
    "\n",
    "# print(dataset)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "dba8cd63",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0     -0.922794\n",
      "1     -0.929073\n",
      "2     -0.673078\n",
      "3     -0.453918\n",
      "4     -0.941319\n",
      "         ...   \n",
      "639    0.332269\n",
      "640   -0.806407\n",
      "641   -0.112514\n",
      "642   -0.797555\n",
      "643   -0.049677\n",
      "Name: X, Length: 644, dtype: float64 0      0.702471\n",
      "1      0.702471\n",
      "2      0.702471\n",
      "3      0.702471\n",
      "4     -0.368982\n",
      "         ...   \n",
      "639   -0.287135\n",
      "640   -0.517795\n",
      "641   -0.517795\n",
      "642   -0.517795\n",
      "643   -0.517795\n",
      "Name: Y, Length: 644, dtype: float64      Unnamed: 0  Subject  Vision Surface\n",
      "0             0        1    Open    Firm\n",
      "1             1        1  Closed    Firm\n",
      "2             2        1    Open    Foam\n",
      "3             3        1  Closed    Foam\n",
      "4             4        2    Open    Firm\n",
      "..          ...      ...     ...     ...\n",
      "639         639      162    Open    Foam\n",
      "640         640      163  Closed    Firm\n",
      "641         641      163    Open    Foam\n",
      "642         642      163    Open    Firm\n",
      "643         643      163  Closed    Foam\n",
      "\n",
      "[644 rows x 4 columns]\n"
     ]
    }
   ],
   "source": [
    "X = dataset['X']\n",
    "y = dataset['Y']\n",
    "other = pd.DataFrame(dataset.iloc[:,:4])\n",
    "# print(X, y, other)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "34aeb1fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "X_ = X.values.reshape(-1, 1) # some algorithms need to reshape X if X has a single feature"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "c1e39e01",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1296, in chi2_kernel\n",
      "    K = additive_chi2_kernel(X, Y)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:190: UserWarning: Singular matrix in solving dual problem. Using least-squares solution instead.\n",
      "  warnings.warn(\"Singular matrix in solving dual problem. Using \"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "------------------ Kernel Ridge Regression Model\n",
      "Best parameter: {'kernel': 'cosine'}\n",
      "Best cross-validation score: -0.15\n",
      "Best estimator: KernelRidge(kernel='cosine')\n",
      "The Index of Best estimator: 31\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 172, in fit\n",
      "    K = self._get_kernel(X)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/kernel_ridge.py\", line 133, in _get_kernel\n",
      "    return pairwise_kernels(X, Y, metric=self.kernel,\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1954, in pairwise_kernels\n",
      "    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1359, in _parallel_pairwise\n",
      "    return func(X, Y, **kwds)\n",
      "  File \"/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/pairwise.py\", line 1245, in additive_chi2_kernel\n",
      "    raise ValueError(\"X contains negative values.\")\n",
      "ValueError: X contains negative values.\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/zclalala/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.19137482 -0.19027057 -0.19170436         nan -0.19039492 -0.19290437\n",
      " -0.1906114  -0.19325671         nan -0.19197976 -0.1942845  -0.20271432\n",
      " -0.19145015         nan -0.18971782 -0.19612849 -0.24974209 -0.19728177\n",
      "         nan -0.25482732 -0.22651813 -0.36795275 -0.19734872         nan\n",
      " -0.41968214 -0.31282168 -0.49460977 -0.19734962         nan -4.20332397\n",
      " -0.15686068 -0.15109876         nan]\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# Kernel ridge regression\n",
    "'''\n",
    "The number of weak learners is controlled by the parameter n_estimators. \n",
    "The learning_rate parameter controls the contribution of the weak learners in the final combination. \n",
    "# kernel = Kernel mapping used internally. This parameter is directly passed to pairwise_kernel. \n",
    "    If kernel is a string, it must be one of the metrics in pairwise.PAIRWISE_KERNEL_FUNCTIONS. \n",
    "    If kernel is “precomputed”, X is assumed to be a kernel matrix. \n",
    "    Alternatively, if kernel is a callable function, it is called on each pair of instances (rows) \n",
    "        and the resulting value recorded. \n",
    "    The callable should take two rows from X as input and return the corresponding kernel value as a single number. \n",
    "# gamma = Gamma parameter for the RBF, laplacian, polynomial, exponential chi2 and sigmoid kernels. \n",
    "    Interpretation of the default value is left to the kernel; see the documentation for sklearn.metrics.pairwise. \n",
    "    Ignored by other kernels.\n",
    "# alpha?\n",
    "'''\n",
    "\n",
    "'''\n",
    "# kernelRidge要考虑的参数是kernel和gamma，通过GridSearchCV我们需要确定param_grid也就是这个参数有哪些值才能找到最佳模型。\n",
    "# np.logspace用于创建等比数列, 开始点和结束点是10的幂, \n",
    "    i.e. logspace(-2,1,4)表示起始数字为10^-2，结尾数字为10^1，元素个数为4的等比数列\n",
    "'''\n",
    "# Set param_grid, aka the main parameters in Ridge\n",
    "param_grid_KernelRidge = [{'kernel':['rbf','laplacian','poly','chi2','sigmoid'],\n",
    "                           'gamma':np.logspace(-3,2,6)},\n",
    "                          {'kernel':['linear','cosine','additive_chi2']}]\n",
    "\n",
    "# GridSearchCV\n",
    "kr = GridSearchCV(estimator=KernelRidge(), # algorithm - Kernel ridge regression\n",
    "                    param_grid=param_grid_KernelRidge, # specify the parameters to search over using a dict or list of dictionaries\n",
    "                    cv=10 # 10-Fold\n",
    "                    )\n",
    "\n",
    "# Build the model\n",
    "kr.fit(X_, y)\n",
    "\n",
    "# Output the best parameter, cross-validation score, estimator, and the index of best estimator.\n",
    "print(\"\\n------------------ Kernel Ridge Regression Model\")\n",
    "print(\"Best parameter: {}\".format(kr.best_params_))\n",
    "print(\"Best cross-validation score: {:.2f}\".format(kr.best_score_))\n",
    "print(\"Average score in 10-Fold: \\n\", kr.cv_results_['mean_test_score'])\n",
    "print(\"Std score in 10-Fold: \\n\", kr.cv_results_['std_test_score'])\n",
    "print(\"Best estimator: {}\".format(kr.best_estimator_))\n",
    "print(\"The Index of Best estimator: {}\".format(kr.best_index_))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bd8a4fd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
